# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'data/mainwindow.ui',
# licensing of 'data/mainwindow.ui' applies.
#
# Created: Fri Aug  9 18:43:27 2019
#      by: pyside2-uic  running on PySide2 5.9.0~a1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(978, 784)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftPushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftPushButton.sizePolicy().hasHeightForWidth())
        self.leftPushButton.setSizePolicy(sizePolicy)
        self.leftPushButton.setObjectName("leftPushButton")
        self.horizontalLayout.addWidget(self.leftPushButton)
        self.rightPushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rightPushButton.sizePolicy().hasHeightForWidth())
        self.rightPushButton.setSizePolicy(sizePolicy)
        self.rightPushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.rightPushButton.setObjectName("rightPushButton")
        self.horizontalLayout.addWidget(self.rightPushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.tabWidget = QtWidgets.QTabWidget(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.scrollArea = QtWidgets.QScrollArea(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 723, 681))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_6.addWidget(self.splitter, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 978, 30))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuedit = QtWidgets.QMenu(self.menubar)
        self.menuedit.setObjectName("menuedit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionOpen_Directory = QtWidgets.QAction(MainWindow)
        self.actionOpen_Directory.setObjectName("actionOpen_Directory")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionSave_Dataset = QtWidgets.QAction(MainWindow)
        self.actionSave_Dataset.setObjectName("actionSave_Dataset")
        self.actionStopwatch_Start = QtWidgets.QAction(MainWindow)
        self.actionStopwatch_Start.setObjectName("actionStopwatch_Start")
        self.actionStopwatch_Stop = QtWidgets.QAction(MainWindow)
        self.actionStopwatch_Stop.setObjectName("actionStopwatch_Stop")
        self.actionStopwatch_Reset = QtWidgets.QAction(MainWindow)
        self.actionStopwatch_Reset.setObjectName("actionStopwatch_Reset")
        self.actionSend_to_left_tab = QtWidgets.QAction(MainWindow)
        self.actionSend_to_left_tab.setObjectName("actionSend_to_left_tab")
        self.actionSend_to_right_tab = QtWidgets.QAction(MainWindow)
        self.actionSend_to_right_tab.setObjectName("actionSend_to_right_tab")
        self.actionPrevious_box = QtWidgets.QAction(MainWindow)
        self.actionPrevious_box.setObjectName("actionPrevious_box")
        self.actionNext_box = QtWidgets.QAction(MainWindow)
        self.actionNext_box.setObjectName("actionNext_box")
        self.actionNext_label = QtWidgets.QAction(MainWindow)
        self.actionNext_label.setObjectName("actionNext_label")
        self.actionPrevious_label = QtWidgets.QAction(MainWindow)
        self.actionPrevious_label.setObjectName("actionPrevious_label")
        self.menuFile.addAction(self.actionOpen_Directory)
        self.menuFile.addAction(self.actionSave_Dataset)
        self.menuFile.addAction(self.actionQuit)
        self.menuTools.addAction(self.actionStopwatch_Start)
        self.menuTools.addAction(self.actionStopwatch_Stop)
        self.menuTools.addAction(self.actionStopwatch_Reset)
        self.menuedit.addAction(self.actionSend_to_left_tab)
        self.menuedit.addAction(self.actionSend_to_right_tab)
        self.menuedit.addAction(self.actionNext_label)
        self.menuedit.addAction(self.actionPrevious_label)
        self.menuView.addAction(self.actionPrevious_box)
        self.menuView.addAction(self.actionNext_box)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuedit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.toolBar.addAction(self.actionOpen_Directory)
        self.toolBar.addAction(self.actionSave_Dataset)
        self.toolBar.addAction(self.actionStopwatch_Start)
        self.toolBar.addAction(self.actionStopwatch_Stop)
        self.toolBar.addAction(self.actionStopwatch_Reset)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Corrector [*]", None, -1))
        self.leftPushButton.setText(QtWidgets.QApplication.translate("MainWindow", "Send to left tab", None, -1))
        self.rightPushButton.setText(QtWidgets.QApplication.translate("MainWindow", "Send to right tab", None, -1))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("MainWindow", "File", None, -1))
        self.menuTools.setTitle(QtWidgets.QApplication.translate("MainWindow", "Tools", None, -1))
        self.menuedit.setTitle(QtWidgets.QApplication.translate("MainWindow", "edit", None, -1))
        self.menuView.setTitle(QtWidgets.QApplication.translate("MainWindow", "View", None, -1))
        self.toolBar.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "toolBar", None, -1))
        self.actionOpen_Directory.setText(QtWidgets.QApplication.translate("MainWindow", "Open Directory", None, -1))
        self.actionOpen_Directory.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Open Directory", None, -1))
        self.actionOpen_Directory.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+O", None, -1))
        self.actionQuit.setText(QtWidgets.QApplication.translate("MainWindow", "Quit", None, -1))
        self.actionQuit.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+Q", None, -1))
        self.actionSave_Dataset.setText(QtWidgets.QApplication.translate("MainWindow", "Save Dataset", None, -1))
        self.actionSave_Dataset.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+S", None, -1))
        self.actionStopwatch_Start.setText(QtWidgets.QApplication.translate("MainWindow", "Stopwatch Start", None, -1))
        self.actionStopwatch_Stop.setText(QtWidgets.QApplication.translate("MainWindow", "Stopwatch Stop", None, -1))
        self.actionStopwatch_Reset.setText(QtWidgets.QApplication.translate("MainWindow", "Stopwatch Reset", None, -1))
        self.actionSend_to_left_tab.setText(QtWidgets.QApplication.translate("MainWindow", "Send to left tab", None, -1))
        self.actionSend_to_left_tab.setShortcut(QtWidgets.QApplication.translate("MainWindow", "S", None, -1))
        self.actionSend_to_right_tab.setText(QtWidgets.QApplication.translate("MainWindow", "Send to right tab", None, -1))
        self.actionSend_to_right_tab.setShortcut(QtWidgets.QApplication.translate("MainWindow", "G", None, -1))
        self.actionPrevious_box.setText(QtWidgets.QApplication.translate("MainWindow", "Previous box", None, -1))
        self.actionPrevious_box.setShortcut(QtWidgets.QApplication.translate("MainWindow", "F", None, -1))
        self.actionNext_box.setText(QtWidgets.QApplication.translate("MainWindow", "Next box", None, -1))
        self.actionNext_box.setShortcut(QtWidgets.QApplication.translate("MainWindow", "D", None, -1))
        self.actionNext_label.setText(QtWidgets.QApplication.translate("MainWindow", "Next label", None, -1))
        self.actionNext_label.setShortcut(QtWidgets.QApplication.translate("MainWindow", "E", None, -1))
        self.actionPrevious_label.setText(QtWidgets.QApplication.translate("MainWindow", "Previous label", None, -1))
        self.actionPrevious_label.setShortcut(QtWidgets.QApplication.translate("MainWindow", "R", None, -1))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

